<section id="" class="container bg-white">
        <div class="col-75">
            <h4 style="text-transform: uppercase; margin-top: 20px;">Acesso rápido</h4>
            <div class="linha2"></div>
            <center>
            <div class="col-12 atalhos1">
               <a href="https://qacademico.ifce.edu.br/">
                    <img id="ImgAtalhos" src="img/academico.png" width="70px" height="70px">
                <h6>Q-Acadêmico</h6>
                </a>
            </div>
            <div class="col-12 atalhos1">
               <a href="http://biblioteca.ifce.edu.br/">
                    <img id="ImgAtalhos" src="img/biblioteca.png" width="70px" height="70px">
                <h6>Biblioteca Virtual</h6>
                </a>
            </div>
            <div class="col-12 atalhos1">
               <a href="https://sisae.ifce.edu.br/">
                    <img id="ImgAtalhos" src="img/sisae.png" width="70px" height="70px">
                <h6>Sisae</h6>
                </a>
            </div>

             <div class="col-12 atalhos1">
               <a href="https://ifce.edu.br/progep/formularios-e-requerimentos">
                    <img id="ImgAtalhos" src="img/formularios.png" width="70px" height="70px">
                <h6>Formulários e requerimentos</h6>
                </a>
            </div> 

            <div class="col-12 atalhos2">
               <a href="https://qselecao.ifce.edu.br/">
                    <img id="ImgAtalhos" src="img/selecao.png" width="70px" height="70px">
                <h6>Q-Seleção</h6>
                </a>
            </div>
            <div class="col-12 atalhos2">
               <a href="https://ifce.edu.br/fortaleza/estagio/colecao-vagas-de-estagio">
                    <img id="ImgAtalhos" src="img/estagios.png" width="70px" height="70px">
                <h6>Estágios e empregos</h6>
                </a>
            </div>
             <div class="col-12 atalhos2">
               <a href="https://ifce.edu.br/espaco-estudante/formularios-e-requerimentos">
                    <img id="ImgAtalhos" src="img/requerimentos.png" width="70px" height="70px">
                <h6>Formulários de estágio</h6>
                </a>
            </div> 
             <div class="col-12 atalhos2">
               <a href="https://ifce.edu.br/fortaleza">
                    <img id="ImgAtalhos" src="img/home.png" width="70px" height="70px">
                <h6>Página oficial IFCE Fortaleza</h6>
                </a>
            </div></center>

            <div class="rsociais"> 
             <h4>Acompanhe o IFCE Fortaleza nas redes sociais</h4>
            <div class="linha4"></div>
            </div>
            <div class="col-10">
               <a href="http://instagram.com/ifceoficial">
                    <img id="ImgAtalhos" src="img/insta.png" width="35px" height="35px">
                </a>
            </div>
            <div class="col-10">
               <a href="https://www.facebook.com/IFCeara/">
                    <img id="ImgAtalhos" src="img/fb.png" width="35px" height="35px">
                </a>
            </div>
            <div class="col-10">
               <a href="https://twitter.com/ifce_">
                    <img id="ImgAtalhos" src="img/tt.png" width="35px" height="35px">
                </a>
            </div>
            <div class="col-10">
               <a href="https://www.youtube.com/user/IFCECOficialComunica">
                    <img id="ImgAtalhos" src="img/yout.png" width="35px" height="35px">
                </a>
            </div>
            <div class="col-10">
               <a href="https://www.flickr.com/photos/reitoriaifce">
                    <img id="ImgAtalhos" src="img/flickr.png" width="35px" height="35px">
                </a>
            </div>
            <div class="col-10">
               <a href="https://soundcloud.com/ifcenoar">
                    <img id="ImgAtalhos" src="img/sound.png" width="35px" height="35px">
                </a>
            </div>
            </div>
        </div>
        <!-- fim do col-75 -->
        <div class="col-25">
            <center>
            <img id="ImgIFCE" src="img/ifce.png" width="150px" height="200px" style="margin-top: 30px;">
             <div class="linha3"></div>           
             <div>
             <h6 style="color: black;">Av. Treze de Maio, 2081, Benfica. Fortaleza - CE. CEP: 60040-215 <br>
              Fone: (85) 3307.3681.</h6>
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2367.2959258821897!2d-38.536958992830435!3d-3.744396198942219!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7c7491a5cfc50e5%3A0x35b7fad8eb59ba84!2sIFCE%20-%20Instituto%20Federal%20do%20Cear%C3%A1%20%7C%20Campus%20Fortaleza!5e0!3m2!1spt-BR!2sbr!4v1589238697785!5m2!1spt-BR!2sbr" width="250" height="200" frameborder="0" style="border:2px solid #3cab87; margin-bottom: 20px;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
             </div>
            </center>

        </div>
        <!-- fim do col-25 -->
    </section>