<div id="terca" class="">
    <nav id="Turnos" class="container">
        <a href="/laboratorios_segunda" class="btn manha">Segunda</a>
        <a href="/laboratorios_terca" class="btn tarde">Terça</a>
        <a href="/laboratorios_quarta" class="btn noite">Quarta</a>
        <a href="/laboratorios_quinta" class="btn noite">Quinta</a>
        <a href="/laboratorios_sexta" class="btn noite">Sexta</a>
    </nav>
    Quar





<?php 

    $lmc1_segunda_noite_1t['laboratorio'] = '';
    $lmc1_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $lmc1_segunda_noite_1t['turma'] = 'Sem turma';
    $lmc1_segunda_noite_1t['disciplina'] = 'Sem disciplina';

    $lmc2_segunda_noite_1t['laboratorio'] = '';
    $lmc2_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $lmc2_segunda_noite_1t['turma'] = 'Sem turma';
    $lmc2_segunda_noite_1t['disciplina'] = 'Sem disciplina';

    $lmc3_segunda_noite_1t['laboratorio'] = '';
    $lmc3_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $lmc3_segunda_noite_1t['turma'] = 'Sem turma';
    $lmc3_segunda_noite_1t['disciplina'] = 'Sem disciplina';

    $lmc4_segunda_noite_1t['laboratorio'] = '';
    $lmc4_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $lmc4_segunda_noite_1t['turma'] = 'Sem turma';
    $lmc4_segunda_noite_1t['disciplina'] = 'Sem disciplina';

    $redes1_segunda_noite_1t['laboratorio'] = '';
    $redes1_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $redes1_segunda_noite_1t['turma'] = 'Sem turma';
    $redes1_segunda_noite_1t['disciplina'] = 'Sem disciplina';

    $redes2_segunda_noite_1t['laboratorio'] = '';
    $redes2_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $redes2_segunda_noite_1t['turma'] = 'Sem turma';
    $redes2_segunda_noite_1t['disciplina'] = 'Sem disciplina';
    
    $semb_segunda_noite_1t['laboratorio'] = '';
    $semb_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $semb_segunda_noite_1t['turma'] = 'Sem turma';
    $semb_segunda_noite_1t['disciplina'] = 'Sem disciplina';

    $semb_segunda_noite_1t['laboratorio'] = '';
    $semb_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $semb_segunda_noite_1t['turma'] = 'Sem turma';
    $semb_segunda_noite_1t['disciplina'] = 'Sem disciplina';

    $elet_segunda_noite_1t['laboratorio'] = '';
    $elet_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $elet_segunda_noite_1t['turma'] = 'Sem turma';
    $elet_segunda_noite_1t['disciplina'] = 'Sem disciplina';

    $comutacao_segunda_noite_1t['laboratorio'] = '';
    $comutacao_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $comutacao_segunda_noite_1t['turma'] = 'Sem turma';
    $comutacao_segunda_noite_1t['disciplina'] = 'Sem disciplina';

    $radio_segunda_noite_1t['laboratorio'] = '';
    $radio_segunda_noite_1t['nome_professor'] = 'Sem professor';
    $radio_segunda_noite_1t['turma'] = 'Sem turma';
    $radio_segunda_noite_1t['disciplina'] = 'Sem disciplina'; 

    foreach ($this->view->horario_segunda as $key => $value) {
    
        if($value['laboratorio'] == 'lmc1' && $value['horario'] == '18:30'){
    
            $lmc1_segunda_noite_1t = $value;
        }else if($value['laboratorio'] == 'lmc2' && $value['horario'] == '18:30'){
    
            $lmc2_segunda_noite_1t= $value;
        }else if($value['laboratorio'] == 'lmc3' && $value['horario'] == '18:30'){
    
            $lmc3_segunda_noite_1t = $value;
        }else if($value['laboratorio'] == 'lmc4' && $value['horario'] == '18:30'){
    
            $lmc4_segunda_noite_1t = $value;
        }else if($value['laboratorio'] == 'redes1' && $value['horario'] == '18:30'){
    
            $redes1_segunda_noite_1t = $value;
        }else if($value['laboratorio'] == 'redes2' && $value['horario'] == '18:30'){
    
            $redes2_segunda_noite_1t = $value;
        }else if($value['laboratorio'] == 'semb' && $value['horario'] == '18:30'){
    
            $semb_segunda_noite_1t = $value;
        }else if($value['laboratorio'] == 'elet' && $value['horario'] == '18:30'){
    
            $elet_segunda_noite_1t = $value;
        }else if($value['laboratorio'] == 'comutacao' && $value['horario'] == '18:30'){
    
            $comutacao_segunda_noite_1t = $value;
        }else if($value['laboratorio'] == 'radio' && $value['horario'] == '18:30'){
    
            $radio_segunda_noite_1t = $value;
        }
    
    }