<div id="terca" class="">
    <nav id="Turnos" class="container">
        <a href="/laboratorios_segunda" class="btn manha">Segunda</a>
        <a href="/laboratorios_terca" class="btn tarde">Terça</a>
        <a href="/laboratorios_quarta" class="btn noite">Quarta</a>
        <a href="/laboratorios_quinta" class="btn noite">Quinta</a>
        <a href="/laboratorios_sexta" class="btn noite">Sexta</a>
    </nav>

    Terça 




    <div class="" id="">
                <!--Primeiro tempo manhã-->
                <div class="TempoManha">
                    <div class="Tempos">
                        <h3 class="text-center">1º Tempo manhã </h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                            <!--LMC 1 => 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc1_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc1_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc1_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>


                                <!--LMC 2-->
                                <!--LMC 2 => 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc2_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc2_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc2_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc3_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc3_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc3_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc4_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc4_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc4_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $redes1_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes1_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes1_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $redes2_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes2_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes2_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $semb_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $semb_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $semb_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Elet-->
                                <!--Elet=> 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">Elet</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $elet_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $elet_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $elet_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Comutação-->
                                <!--Comutação => 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">Comutação</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $comutacao_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $comutacao_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $comutacao_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Radio-->
                                <!--Rádio => 10:00 as 12:00-->
                                <tr>
                                    <td class="NomeLab">Rádio</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $radio_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $radio_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $radio_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
            </div>
</div>