<?php
    # Campos padrão para cada laboratorio .
    require_once('camposPadrao_segunda.php');

    if(isset($_SESSION['id_usuario'])){
        $logado = true;
    }else {
        $logado = false;
    }

    foreach ($this->view->bolsistas as $key => $value) {
        
        echo '<pre>';
        print_r($value['nome_bolsista']);
        echo '</pre>';
    }
?>
    <nav id="" class="container" style="margin-top: 20px;">
        <a href="/laboratorios_segunda" class="btn manha">Segunda</a>
        <a href="/laboratorios_terca" class="btn tarde">Terça</a>
        <a href="/laboratorios_quarta" class="btn noite">Quarta</a>
        <a href="/laboratorios_quinta" class="btn noite">Quinta</a>
        <a href="/laboratorios_sexta" class="btn noite">Sexta</a>
    </nav>

<section style="margin-top: 20px;">

    <h3>Horarios da segunda-feira</h3>

    <nav id="Turnos" class="container">
        <button id="Manha" class="btn manha">Manhã</button>
        <button id="Tarde" class="btn tarde">Tarde</button>
        <button id="Noite" class="btn noite">Noite</button>
    </nav>

    <!--Tabela com os horarios-->
    <div id="TabelaHorarios">
        
        
        <!--Tabela da Manhã-->
        <div class="" id="Manha">      
            <!--Primeiro tempo manhã-->
            <div class="TempoManha">
                <div class="Tempos">
                    <h3 class="text-center">1º Tempo manhã </h3>
                </div>
            <form action="/situacao_laboratorio" method="post">
                <div class="table-responsive">
                    <table class="table table-striped ">
                        <thead class="thead-dark">
                            <!--heades da tabela-->
                            <tr>
                                <th class="NomeLab">Laboratório</th>
                                <th>Horarios</th>
                                <th>Professor</th>
                                <th>Turma</th>
                                <th>Disciplina</th>
                                <th>Bolsista</th>
                                <th>Situação</th>
                            </tr>
                        </thead>

                            <tbody>
                            <!--LMC 1 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $lmc1_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc1_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc1_segunda_manha_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td>  
                                        <?php if($logado) {?>                                  
                                            <select name="bolsista_lmc1" id="Dropdown_para_opcoes">
                                                <?php foreach ($this->view->bolsistas as $key => $value) { ?>                                                
                                                    <option><?= $value['nome_bolsista'] ?></option>                                         
                                                <?php }?>
                                            </select>                                    
                                        <?php }?>
                                    </td>
                                    <td>
                                        <select name="situacao_lmc1" id="Dropdown_para_opcoes">
                                            <option>Fechado</option>
                                            <option>Em aula</option>
                                            <option>Livre</option>
                                            <option>Reservado</option>
                                        </select>
                                    </td>
                                </tr>


                                <!--LMC 2-->
                                <!--LMC 2 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $lmc2_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc2_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc2_segunda_manha_1t['disciplina'] ?></td>  
                                    <!--Bolsistas-->
                                    
                                    <td>  
                                        <?php if($logado) {?>                                  
                                            <select name="bolsista_lmc2" id="Dropdown_para_opcoes">
                                                <?php foreach ($this->view->bolsistas as $key => $value) { ?>                                                
                                                    <option><?= $value['nome_bolsista'] ?></option>                                         
                                                <?php }?>
                                            </select>                                    
                                        <?php }?>
                                    </td>
                                    <td>
                                        <select name="situacao_lmc2" id="Dropdown_para_opcoes">
                                            <option>Fechado</option>
                                            <option>Em aula</option>
                                            <option>Livre</option>
                                            <option>Reservado</option>
                                        </select>
                                    </td>
                                                                    
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $lmc3_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc3_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc3_segunda_manha_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $lmc4_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc4_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc4_segunda_manha_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $redes1_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes1_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes1_segunda_manha_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $redes2_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes2_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes2_segunda_manha_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $semb_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $semb_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $semb_segunda_manha_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Elet-->
                                <!--Elet=> 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Elet</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $elet_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $elet_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $elet_segunda_manha_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Comutação-->
                                <!--Comutação => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Comutação</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $comutacao_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $comutacao_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $comutacao_segunda_manha_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Radio-->
                                <!--Rádio => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Rádio</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td><?= $radio_segunda_manha_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $radio_segunda_manha_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $radio_segunda_manha_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <form>
            </div>



            <button type="submit">ATT</button>



            <!--Segund0 tempo manhã-->
            <div class="TempoManha">
                <div class="Tempos">
                    <h3 class="text-center">2º Tempo manhã </h3>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped ">
                        <thead class="thead-dark">
                            <!--heades da tabela-->
                            <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                            </tr>
                        </thead>

                        <tbody>
                            <!--LMC 1 => 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc1_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc1_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc1_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>


                                <!--LMC 2-->
                                <!--LMC 2 => 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc2_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc2_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc2_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc3_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc3_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc3_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc4_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc4_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc4_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $redes1_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes1_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes1_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $redes2_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes2_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes2_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                                <!--Semb-->
                                <!--Semb => 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $semb_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $semb_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $semb_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                                <!--Elet-->
                                <!--Elet=> 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">Elet</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $elet_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $elet_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $elet_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                                <!--Comutação-->
                                <!--Comutação => 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">Comutação</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $comutacao_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $comutacao_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $comutacao_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                                <!--Radio-->
                                <!--Rádio => 10:00 as 12:00-->
                            <tr>
                                    <td class="NomeLab">Rádio</td>
                                    <!--Horario da aula-->
                                    <td>10:00 - 12:00</td>
                                    <!--Professor-->
                                    <td><?= $radio_segunda_manha_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $radio_segunda_manha_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $radio_segunda_manha_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
            
        <!--Tabela da Tarde-->
        <div class="" id="Tarde">
            
            <!--Primeiro tempo tarde-->
            <div class="TempoManha">
                <div class="Tempos">
                    <h3 class="text-center">1º Tempo tarde </h3>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                            <!--LMC 1 => 13:30 as152300-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $lmc1_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc1_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc1_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>


                                <!--LMC 2-->
                                <!--LMC 2 => 13:30 as152300-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $lmc2_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc2_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc2_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 13:30 as152300-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $lmc3_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc3_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc3_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 13:30 as152300-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $lmc4_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc4_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc4_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 13:30 as152300-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $redes1_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes1_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes1_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 13:30 as152300-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $redes2_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes2_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes2_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 13:30 as152300-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $semb_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $semb_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $semb_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Elet-->
                                <!--Elet=> 13:30 as152300-->
                                <tr>
                                    <td class="NomeLab">Elet</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $elet_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $elet_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $elet_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Comutação-->
                                <!--Comutação => 13:30 as152300-->
                                <tr>
                                    <td class="NomeLab">Comutação</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $comutacao_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $comutacao_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $comutacao_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Radio-->
                                <!--Rádio => 13:30 as 15:30-->
                                <tr>
                                    <td class="NomeLab">Rádio</td>
                                    <!--Horario da aula-->
                                    <td>13:30 - 15:30</td>
                                    <!--Professor-->
                                    <td><?= $radio_segunda_tarde_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $radio_segunda_tarde_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $radio_segunda_tarde_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>    

                <!--Segundo tempo tarde-->
                <div class="TempoManha">
                    <div class="Tempos">
                        <h3 class="text-center">2º Tempo tarde </h3>
                    </div>
                <div class="table-responsive">
                    <table class="table table-striped ">
                        <thead class="thead-dark">
                            <!--heades da tabela-->
                            <tr>
                                <th class="NomeLab">Laboratório</th>
                                <th>Horarios</th>
                                <th>Professor</th>
                                <th>Turma</th>
                                <th>Disciplina</th>
                                <th>Bolsista</th>
                                <th>Situação</th>
                            </tr>
                        </thead>

                            <tbody>
                            <!--LMC 1 => 16:00 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc1_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc1_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc1_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>


                                <!--LMC 2-->
                                <!--LMC 2 => 16:00 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc2_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc2_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc2_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 16:00 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc3_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc3_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc3_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 16:00 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc4_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc4_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc4_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 16:00 as18:00-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $redes1_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes1_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes1_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 16:00 as18:00-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $redes2_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes2_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes2_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 16:00 as 18:00-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $semb_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $semb_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $semb_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Elet-->
                                <!--Elet=> 16:00 as18:00-->
                                <tr>
                                    <td class="NomeLab">Elet</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $elet_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $elet_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $elet_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Comutação-->
                                <!--Comutação => 16:00 as18:00-->
                                <tr>
                                    <td class="NomeLab">Comutação</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $comutacao_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $comutacao_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $comutacao_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Radio-->
                                <!--Rádio => 16:00 as 15:30-->
                                <tr>
                                    <td class="NomeLab">Rádio</td>
                                    <!--Horario da aula-->
                                    <td>16:00 - 18:00</td>
                                    <!--Professor-->
                                    <td><?= $radio_segunda_tarde_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $radio_segunda_tarde_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $radio_segunda_tarde_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>     

        <!-- Tabela noite -->
        <div class="" id="Noite">
            
            <!--Primeiro tempo noite-->
            <div class="TempoManha">
                <div class="Tempos">
                    <h3 class="text-center">1º Tempo noite </h3>
                </div>
                    <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                            <!--LMC 1 => 18:30 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $lmc1_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc1_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc1_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>


                                <!--LMC 18:30-->
                                <!--LMC 18:30 => 18:30 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $lmc2_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc2_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc2_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 18:30 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $lmc3_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc3_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc3_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 18:30 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $lmc4_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc4_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc4_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 18:30 as18:00-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $redes1_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes1_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes1_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 18:30-->
                                <!--Redes 3 => 18:30 as18:00-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $redes2_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes2_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes2_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 18:30 as 18:00-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $semb_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $semb_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $semb_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Elet-->
                                <!--Elet=> 18:30 as18:00-->
                                <tr>
                                    <td class="NomeLab">Elet</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $elet_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $elet_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $elet_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Comutação-->
                                <!--Comutação => 18:30 as18:00-->
                                <tr>
                                    <td class="NomeLab">Comutação</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $comutacao_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $comutacao_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $comutacao_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Radio-->
                                <!--Rádio => 18:30 as 20:15-->
                                <tr>
                                    <td class="NomeLab">Rádio</td>
                                    <!--Horario da aula-->
                                    <td>18:30 - 20:15</td>
                                    <!--Professor-->
                                    <td><?= $radio_segunda_noite_1t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $radio_segunda_noite_1t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $radio_segunda_noite_1t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                
                <!--Segunda tempo noite-->
                <div class="TempoManha">
                    <div class="Tempos">
                        <h3 class="text-center">2º Tempo noite </h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                            <!--LMC 1 => 20:15 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc1_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc1_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc1_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>


                                <!--LMC 20:15-->
                                <!--LMC 20:15 => 20:15 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc2_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc2_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc2_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 20:15 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc3_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc3_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc3_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 20:15 as18:00-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $lmc4_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $lmc4_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $lmc4_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 20:15 as18:00-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $redes1_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes1_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes1_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 20:15-->
                                <!--Redes 3 => 20:15 as18:00-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $redes2_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $redes2_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $redes2_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 20:15 as 18:00-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $semb_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $semb_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $semb_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Elet-->
                                <!--Elet=> 20:15 as18:00-->
                                <tr>
                                    <td class="NomeLab">Elet</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $elet_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $elet_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $elet_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Comutação-->
                                <!--Comutação => 20:15 as18:00-->
                                <tr>
                                    <td class="NomeLab">Comutação</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $comutacao_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $comutacao_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $comutacao_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Radio-->
                                <!--Rádio => 20:15 as 22:00-->
                                <tr>
                                    <td class="NomeLab">Rádio</td>
                                    <!--Horario da aula-->
                                    <td>20:15 - 22:00</td>
                                    <!--Professor-->
                                    <td><?= $radio_segunda_noite_2t['nome_professor'] ?></td>
                                    <!--Turma-->
                                    <td><?= $radio_segunda_noite_2t['turma'] ?></td>
                                    <!--Disciplina-->
                                    <td><?= $radio_segunda_noite_2t['disciplina'] ?></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>     
        </div>
</section>













<!--Codigos em javaScript -->
<script>
    function tableshowhide(a, b, c) {
        len = Turnos.childElementCount;
        closeTabelaHorarios();
        for (i = 0; i < len; i++) {
            Turnos.children[i].onclick = function() {
                closeTabelaHorarios();
                TabelaHorarios.children[this.id].style.display = "block";
            }
        }

        function closeTabelaHorarios() {
            for (i = 0; i < TabelaHorarios.childElementCount; i++) {
                TabelaHorarios.children[i].style.display = "none";
            }
        }

        Turnos.children[c].click();
    }

    tableshowhide("menu", "TabelaHorarios", "Manha");
</script>