<!--Escolha do horario para visualizar-->
<section>
        <nav id="Turnos" class="container">
            <button id="Manha" class="btn manha">Manhã</button>
            <button id="Tarde" class="btn tarde">Tarde</button>
            <button id="Noite" class="btn noite">Noite</button>
        </nav>

        <!--Tabela com os horarios-->
        <div id="TabelaHorarios" class="">
            <!--Tabela da Manhã-->
            <div class="" id="Manha">
                <!--Primeiro tempo manhã-->
                <div class="TempoManha">
                    <div class="Tempos">
                        <h3 class="text-center">1º Tempo manhã </h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                                <!--LMC 1 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td>Ajalmar</td>
                                    <!--Turma-->
                                    <td>Informática</td>
                                    <!--Disciplina-->
                                    <td>Estrutura de dados</td>
                                    <!--Bolsistas-->
                                    <td>Alyne</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--LMC 2-->
                                <!--LMC 2 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td>Janaina</td>
                                    <!--Turma-->
                                    <td>Telecomunicações</td>
                                    <!--Disciplina-->
                                    <td>Redes de Computadores</td>
                                    <!--Bolsistas-->
                                    <td>Sem Bolsista</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td>Sem professor</td>
                                    <!--Turma-->
                                    <td>Sem aula</td>
                                    <!--Disciplina-->
                                    <td>Sem aula</td>
                                    <!--Bolsistas-->
                                    <td>Taveira</td>
                                    <!--Situação do lab-->
                                    <td>Livre para estudo</td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td>José Roberto</td>
                                    <!--Turma-->
                                    <td>Eng. de Comput</td>
                                    <!--Disciplina-->
                                    <td>SOR1</td>
                                    <!--Bolsistas-->
                                    <td>Lucas</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td>Hairon</td>
                                    <!--Turma-->
                                    <td>Eng. de Telecomunicações</td>
                                    <!--Disciplina-->
                                    <td>Banco de dados</td>
                                    <!--Bolsistas-->
                                    <td>Sem bolsista</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td>Taveira</td>
                                    <!--Turma-->
                                    <td>Eng. de Comput</td>
                                    <!--Disciplina-->
                                    <td>POO</td>
                                    <!--Bolsistas-->
                                    <td>Lara fit</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>7h30 - 9h30</td>
                                    <!--Professor-->
                                    <td>Bento</td>
                                    <!--Turma-->
                                    <td>Informática</td>
                                    <!--Disciplina-->
                                    <td>Eletrônica analogica</td>
                                    <!--Bolsistas-->
                                    <td>Sem bolsista</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="TempoManha">
                    <div class="Tempos">
                        <h3 class="text-center espacamento_turnos">2º Tempo manhã </h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                                <!--LMC 1 => 10h00 as 12h00-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>10h00 - 12h00</td>
                                    <!--Professor-->
                                    <td>Ajalmar</td>
                                    <!--Turma-->
                                    <td>Informática</td>
                                    <!--Disciplina-->
                                    <td>Estrutura de dados</td>
                                    <!--Bolsistas-->
                                    <td>Alyne</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--LMC 2-->
                                <!--LMC 2 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>10h00 - 12h00</td>
                                    <!--Professor-->
                                    <td>Janaina</td>
                                    <!--Turma-->
                                    <td>Telecomunicações</td>
                                    <!--Disciplina-->
                                    <td>Redes de Computadores</td>
                                    <!--Bolsistas-->
                                    <td>Sem Bolsista</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>10h00 - 12h00</td>
                                    <!--Professor-->
                                    <td>Sem professor</td>
                                    <!--Turma-->
                                    <td>Sem aula</td>
                                    <!--Disciplina-->
                                    <td>Sem aula</td>
                                    <!--Bolsistas-->
                                    <td>Taveira</td>
                                    <!--Situação do lab-->
                                    <td>Livre para estudo</td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>10h00 - 12h00</td>
                                    <!--Professor-->
                                    <td>José Roberto</td>
                                    <!--Turma-->
                                    <td>Eng. de Comput</td>
                                    <!--Disciplina-->
                                    <td>SOR1</td>
                                    <!--Bolsistas-->
                                    <td>Lucas</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>10h00 - 12h00</td>
                                    <!--Professor-->
                                    <td>Hairon</td>
                                    <!--Turma-->
                                    <td>Eng. de Telecomunicações</td>
                                    <!--Disciplina-->
                                    <td>Banco de dados</td>
                                    <!--Bolsistas-->
                                    <td>Sem bolsista</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>10h00 - 12h00</td>
                                    <!--Professor-->
                                    <td>Taveira</td>
                                    <!--Turma-->
                                    <td>Eng. de Comput</td>
                                    <!--Disciplina-->
                                    <td>POO</td>
                                    <!--Bolsistas-->
                                    <td>Lara fit</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>10h00 - 12h00</td>
                                    <!--Professor-->
                                    <td>Bento</td>
                                    <!--Turma-->
                                    <td>Informática</td>
                                    <!--Disciplina-->
                                    <td>Eletrônica analogica</td>
                                    <!--Bolsistas-->
                                    <td>Sem bolsista</td>
                                    <!--Situação do lab-->
                                    <td>Em aula</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!--Tabela da Tarde-->
            <div class="" id="Tarde">
                <!--Primeiro tempo manhã-->
                <div class="TempoManha">
                    <div class="Tempos">
                        <h3 class="text-center">1º Tempo tarde </h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                                <!--LMC 1 => 13h00 as 15h30-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>13h30 - 15h30</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 2-->
                                <!--LMC 2 => 13h30 - 15h30-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>13h30 - 15h30</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 13h30 - 15h30-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>13h30 - 15h30</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 13h30 - 15h30-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>13h30 - 15h30</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 13h30 - 15h30-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>13h30 - 15h30</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 13h30 - 15h30-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>13h30 - 15h30</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 13h30 - 15h30-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>13h30 - 15h30</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="TempoManha">
                    <div class="Tempos">
                        <h3 class="text-center espacamento_turnos">2º Tempo Tarde </h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                                <!--LMC 1 => 16h00 as 18h00-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>16h00 - 18h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 2-->
                                <!--LMC 2 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>16h00 - 18h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>16h00 - 18h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>16h00 - 18h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>16h00 - 18h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>16h00 - 18h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>16h00 - 18h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!--Tabela da Noite-->
            <div class="" id="Noite">
                <div class="TempoManha">
                    <div class="Tempos">
                        <h3 class="text-center">1º Tempo Noite</h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                                <!--LMC 1 => 18h00 as 20h00-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>18h30 - 20h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 2-->
                                <!--LMC 2 => 18h00 as 20h00-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>18h30 - 20h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 18h00 as 20h00-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>18h30 - 20h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 18h00 as 20h00-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>18h30 - 20h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 18h00 as 20h00-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>18h30 - 20h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 18h00 as 20h00-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>18h30 - 20h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 18h00 as 20h00-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>18h30 - 20h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="TempoManha">
                    <div class="Tempos">
                        <h3 class="text-center espacamento_turnos">2º Tempo Noite </h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead class="thead-dark">
                                <!--heades da tabela-->
                                <tr>
                                    <th class="NomeLab">Laboratório</th>
                                    <th>Horarios</th>
                                    <th>Professor</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Bolsista</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>

                            <tbody>
                                <!--LMC 1 => 20h15 as 22h00-->
                                <tr>
                                    <td class="NomeLab">LMC 1</td>
                                    <!--Horario da aula-->
                                    <td>20h15 - 22h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 2-->
                                <!--LMC 2 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 2</td>
                                    <!--Horario da aula-->
                                    <td>20h15 - 22h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 3-->
                                <!--LMC 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 3</td>
                                    <!--Horario da aula-->
                                    <td>20h15 - 22h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--LMC 4-->
                                <!--LMC 4 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">LMC 4</td>
                                    <!--Horario da aula-->
                                    <td>20h15 - 22h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 1-->
                                <!--Redes 1 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 1</td>
                                    <!--Horario da aula-->
                                    <td>20h15 - 22h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Redes 2-->
                                <!--Redes 3 => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Redes 2</td>
                                    <!--Horario da aula-->
                                    <td>20h15 - 22h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                                <!--Semb-->
                                <!--Semb => 7h30 as 9h30-->
                                <tr>
                                    <td class="NomeLab">Semb</td>
                                    <!--Horario da aula-->
                                    <td>20h15 - 22h00</td>
                                    <!--Professor-->
                                    <td></td>
                                    <!--Turma-->
                                    <td></td>
                                    <!--Disciplina-->
                                    <td></td>
                                    <!--Bolsistas-->
                                    <td></td>
                                    <!--Situação do lab-->
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

     <!--Codigos em javaScript-->
     <script>
        function tableshowhide(a, b, c) {
            len = Turnos.childElementCount;
            closeTabelaHorarios();
            for (i = 0; i < len; i++) {
                Turnos.children[i].onclick = function() {
                    closeTabelaHorarios();
                    TabelaHorarios.children[this.id].style.display = "block";
                }
            }

            function closeTabelaHorarios() {
                for (i = 0; i < TabelaHorarios.childElementCount; i++) {
                    TabelaHorarios.children[i].style.display = "none";
                }
            }

            Turnos.children[c].click();
        }

        tableshowhide("menu", "TabelaHorarios", "Manha");
    </script>