<div id="terca" class="">

    <nav id="Turnos" class="container">
        <a href="/laboratorios_segunda" class="btn manha">Segunda</a>
        <a href="/laboratorios_terca" class="btn tarde">Terça</a>
        <a href="/laboratorios_quarta" class="btn noite">Quarta</a>
        <a href="/laboratorios_quinta" class="btn noite">Quinta</a>
        <a href="/laboratorios_sexta" class="btn noite">Sexta</a>
    </nav>
    Sexta       
</div>