<?php

    /*
    foreach ($this->view->bolsistas as $key => $value) {
        # code...
        echo '<pre>';
        print_r($value);
        echo '</pre>';
    }
        */
?>  

<div class="">
    <h3 class="text-center" style="margin-top: 15px">Cadastro de todos os bolsistas</h3>
</div>
    
<section style="margin-bottom: 20px">
    <?php foreach ($this->view->bolsistas as $key => $value) { ?>
        <div class="container" style="border: 3px solid #4ECCA3; margin-top: 10px;">
            <div class="row">
                <div class="col-40">
                    <label for="nome">Nome: </label>
                </div>
                <div>
                    <label><?= $value['nome_bolsista']?></label>
                </div>
            </div>

            <div class="row">
                <div class="col-40">
                    <label for="turno">Turno: </label>
                </div>
                <div>
                    <label><?= $value['turno']?></label>
                </div>
            </div>
            <div class="row">
                <div class="col-40">
                    <label for="email">E-mail:</label>
                </div>
                <div>
                    <label><?= $value['email_bolsista']?></label>
                </div>
            </div>

            <div class="row d-flex justify-content-end">
                <div >
                    <a href="" style="margin-right: 15px">
                        <i class="fas fa-cogs" onclick="editar()"></i>             
                    </a>
                </div>
                <div class="" style="margin-right: 15px">
                    <a href="/apagar_bolsista?id=<?= $value['id_bolsista']?>">
                        <i class="far fa-trash-alt text-danger"></i>              
                    </a>
                </div>                
            </div>
        </div>     
    <?php }?>
</section>
 